version: '3'

services:
  backend:
    container_name: backend_api
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/app/qa_interview
    networks:
      - davu-network
  frontend:
    container_name: frontend_app
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "8001:8001"
    environment:
      - BACKEND_HOST=http://backend:8000
    volumes:
      - ./:/app/qa_interview
    networks:
      - davu-network
networks:
  davu-network:
    driver: bridge
